package com.example.teacherApp.Enums;

public enum Subjects {

    MATHEMATICS,
    PHYSICS_AND_CHEMISTRY,
    LIFE_AND_EARTH_NATURAL_SCIENCES,
    HISTORY_AND_GEOGRAPHY,
    PHILOSOPHY,
    SOCIAL_STUDIES,
    ARABIC,
    AMAZIGH,
    ISLAMIC_EDUCATION,
    ART_EDUCATION,
    ENGLISH,
    FRENCH,
    PHYSICAL_EDUCATION,
    SCIENCE_AND_TECHNOLOGY,
    COMPUTER_SCIENCE

}
